server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: service-one
  profiles:
    default: "none"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
